basic.showIcon(IconNames.Heart)
SuperBit.MotorRunDual(
SuperBit.enMotors.M1,
10,
SuperBit.enMotors.M3,
10
)
basic.showIcon(IconNames.Heart)
SuperBit.MotorRunDual(
SuperBit.enMotors.M1,
10,
SuperBit.enMotors.M1,
5
)
